parameters:
    secret: ThisTokenIsNotSoSecretChangeIt

services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: true

    OpenDxp\Bundle\PersonalizationBundle\Installer:
        public: true
        arguments:
            $bundle: "@=service('kernel').getBundle('OpenDxpPersonalizationBundle')"
